services:
  # Banco de dados PostgreSQL (Rodando estritamente no Manager)
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: forca
      POSTGRES_PASSWORD: forca
      POSTGRES_DB: forca
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forca-net
    deploy:
      placement:
        constraints:
          - node.role == manager

  # Servidor Redis necessário para a fila (Rodando estritamente no Manager)
  redis:
    image: redis:alpine
    networks:
      - forca-net
    deploy:
      placement:
        constraints:
          - node.role == manager

  # Backend Node.js (Replicado pelos Workers)
  backend:
    image: my-hangman-backend:v2 # Versão fixa para evitar cache de 'latest'
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://forca:forca@postgres:5432/forca
    networks:
      - forca-net
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure

  # Frontend React/Vite
  frontend:
    image: my-hangman-frontend:v2 # Versão fixa para evitar cache de 'latest'
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    networks:
      - forca-net

networks:
  forca-net:
    driver: overlay

volumes:
  postgres_data:
